Add /rounds/add to allow adding new rounds to system.
infinityworks/snailx_admin_panel pull request #11
Opened 2018-10-26 12:22 UTC by sorsby

- Create form to input name and dates of a new round.
- Add validation to the form data.
- Add tests for the new functionality.
- Change styling for login page.
- Add logic to models.py to retrieve current active round and update /rounds page to reflect this change.

2018-10-26 13:32 UTC, MikeSilverstone requested changes

2018-10-26 13:32 UTC, MikeSilverstone commented on snailx_admin.py
> +    port = int(os.environ.get('PORT', 5001))
If you're changing this, don't forget to change the vagrant file

2018-10-26 13:51 UTC, MikeSilverstone submitted a review, later dismissed

2018-10-26 13:51 UTC, MikeSilverstone commented on db/models.py
>  from globals.globals import db, login_manager
When adding a new round I get error: https://pastebin.com/hLe1RxFW

2018-10-29 14:54 UTC, infinitydeep requested changes
It should not be possible to add rounds with the same name - please correct
The max length of chars for a round is 12, however the code does not allow for it to be 12
Rounds should not overlap in terms of when they are played - they should be in completely separate time periods. Please update to validate this

2018-10-29 15:41 UTC, infinitydeep approved these changes

2018-10-29 15:42 UTC, merged